<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH . '/libraries/REST_Controller.php';

class Bogie_Api extends REST_Controller
{
    var $authorization = null;

    function __construct()
    {
        parent::__construct();

        // Configure limits on our controller methods
        // Ensure you have created the 'limits' table and enabled 'limits' within application/config/rest.php
        $this->methods['bogie_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['bogie_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['bogie_put']['limit'] = 50; // 50 requests per hour per user/key
        $this->methods['bogie_delete']['limit'] = 50; // 50 requests per hour per user/key

        header('Access-Control-Allow-Origin: *');
        header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method, Authorization");
        header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");

/*
        if ( "OPTIONS" === $_SERVER['REQUEST_METHOD'] )
            die();
        if(!$this->input->get_request_header('Authorization'))
            $this->response(null, 400);
        $this->authorization = $this->input->get_request_header('Authorization');
        */

        $this->load->model("Bogie_Model");
    }

    public function bogie_get()
    {
        $bogies = null;

        $id = $this->get('id');

        if ($id === NULL)        {
            $bogies = $this->Bogie_Model->GetData();
            if ($bogies)            {
                $this->response($bogies, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            }            else            {
                $this->response([
                    'status' => FALSE,
                    'message' => 'No data were found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        }

        $id = (int) $id;
        if ($id <= 0)
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code

        $bogie = $this->Bogie_Model->GetDataById($id);
        if (!empty($bogie)) {
            $this->set_response($bogie, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
        } else {
            $this->set_response([
                'status' => FALSE,
                'message' => 'User could not be found'
            ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
        }
    }

    public function bogie_post() {

        $entity = $this->post();
        $this->Bogie_Model->Insert($entity);

        $message = [
            'id' => 100, // Automatically generated by the model
            'message' => 'Added a resource'
        ];

        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }

    public function bogie_put() {
        $entity = $this->put();
        $entity->UPDATE_DATE = getDateNow();
        $entity->UPDATE_USER = "T931";
        $this->Bogie_Model->Update($entity);

        $message = [
            'id' => 100, // Automatically generated by the model
            'message' => 'A resource has updated'
        ];

        $this->set_response($message, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
    }

    public function bogie_delete() {
        $id = (int) $this->get('id');

        if ($id <= 0)
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code

        $this->Bogie_Model->Delete($id);
        $message = [
            'id' => $id,
            'message' => 'the resource was deleted'
        ];

        $this->set_response($message, REST_Controller::HTTP_NO_CONTENT); // NO_CONTENT (204) being the HTTP response code
    }
}